#ifndef DOLPHIN_EMU_OPERATIONTYPE_H
#define DOLPHIN_EMU_OPERATIONTYPE_H

enum class OperationType : char {
    SET_OPPONENT_RACER_ID,
    LOAD_RACE,
    BEGIN_COUNTDOWN,
    SET_RACER_BLOCK,
};

#endif //DOLPHIN_EMU_OPERATIONTYPE_H
